import type { Metadata } from "next";
import { Inder } from "next/font/google";
import "./styles/globals.scss";

const inder = Inder({
  subsets: ['latin'],
  weight: ['400']
});

export const metadata: Metadata = {
  title: "Detection Scooter",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inder.className}>
        {children}
      </body>
    </html>
  );
}
